#!/bin/bash
cd /home/ec2-user
#Install Packages
sudo amazon-linux-extras install epel -y
sudo yum update -y
sudo yum install git pdsh -y


#Setup PDSH variables
echo 'export PDSH_RCMD_TYPE=ssh' >> /home/ec2-user/.bashrc
echo 'export WCOLL=~/weka_clients.host'  >> /home/ec2-user/.bashrc
weka user login david AWs_*321!
weka cluster servers list --role=backend -o hostname --no-header > /home/ec2-user/weka_cluster.host
weka cluster servers list --role=client -o hostname --no-header > /home/ec2-user/weka_clients.host
weka user delete david

#Setup SSH 
echo " StrictHostKeyChecking no" >> /home/ec2-user/.ssh/config
chmod 400 /home/ec2-user/.ssh/config

# Install WEKA Tools
mkdir /home/ec2-user/tools
git clone https://github.com/weka/tools
